export const voucherShortcuts = [
  { primary: "F2", alternate: "D", label: "Date", focusTarget: "[data-voucher-date='true']" },
  { primary: "F4", alternate: "C", label: "Contra", route: "/transactions/accounting/contra" },
  { primary: "F5", alternate: "M", label: "Payment", route: "/transactions/accounting/payment" },
  { primary: "F6", alternate: "R", label: "Receipt", route: "/transactions/accounting/receipt" },
  { primary: "F7", alternate: "J", label: "Journal", route: "/transactions/accounting/journal" },
  { primary: "F8", alternate: "S", label: "Sales", route: "/transactions/accounting/sales" },
  { primary: "F9", alternate: "H", label: "Purchase", route: "/transactions/accounting/purchase" },
  { primary: "F10", alternate: "O", label: "POS Voucher", route: "/transactions/accounting/pos-voucher" },
  { primary: "+", alternate: "A", label: "Add Row", action: "addRow" },
  { primary: "Tab", alternate: "V", label: "Save Voucher", action: "saveVoucher" },
];

export const sidebarParentShortcuts = [
  { key: "d", label: "Dashboard", route: "/", scope: "Dashboard", openKey: "Dashboard" },
  { key: "y", label: "Company", scope: "Company" },
  { key: "g", label: "Create", scope: "Masters/Create", openKey: "Masters/Create" },
  { key: "m", label: "Alter", scope: "Masters/Alter", openKey: "Masters/Alter" },
  { key: "h", label: "Chart of Accounts", scope: "Chart of Accounts" },
  {
    key: "j",
    label: "Accounting Vouchers",
    scope: "Transactions (Vouchers)/Accounting Vouchers",
    openKey: "Transactions (Vouchers)/Accounting Vouchers",
  },
  {
    key: "i",
    label: "Inventory Vouchers",
    scope: "Transactions (Vouchers)/Inventory Vouchers",
    openKey: "Transactions (Vouchers)/Inventory Vouchers",
  },
  { key: "e", label: "Alter Vouchers", route: "/transactions/alter-vouchers" },
  {
    key: "b",
    label: "Financial Statements",
    scope: "Reports/Financial Statements",
    openKey: "Reports/Financial Statements",
  },
  {
    key: "n",
    label: "Inventory Books",
    scope: "Reports/Inventory Books",
    openKey: "Reports/Inventory Books",
  },
  {
    key: "k",
    label: "Account Books",
    scope: "Reports/Account Books",
    openKey: "Reports/Account Books",
  },
  {
    key: "w",
    label: "Customer Behaviour",
    scope: "Reports/Customer Behaviour",
    openKey: "Reports/Customer Behaviour",
  },
  { key: "u", label: "Utilities", scope: "Utilities" },
  { key: "q", label: "All Short Keys", route: "/shortcuts" },
];

export const sidebarChildShortcuts = {
  Dashboard: [
    { key: "r", label: "Regular Dashboard", route: "/" },
    { key: "m", label: "Manufacturing Dashboard", route: "/dashboard/manufacturing" },
  ],
  Company: [
    { key: "c", label: "Create Company", route: "/company/create" },
    { key: "a", label: "Alter Company", route: "/company/alter" },
    { key: "s", label: "Select Company", route: "/company/select" },
    { key: "h", label: "Shut Company", route: "/company/shut" },
    { key: "b", label: "Backup", route: "/company/backup" },
    { key: "r", label: "Restore", route: "/company/restore" },
  ],
  "Masters/Create": [
    { key: "g", label: "Group", route: "/masters/create/group" },
    { key: "l", label: "Ledger", route: "/masters/create/ledger" },
    { key: "v", label: "Voucher Type", route: "/masters/create/voucher-type" },
    { key: "c", label: "Currency", route: "/masters/create/currency" },
    { key: "k", label: "Cost Category", route: "/masters/create/cost-category" },
    { key: "n", label: "Cost Centre", route: "/masters/create/cost-centre" },
    { key: "e", label: "Employee", route: "/masters/create/employee" },
    { key: "b", label: "BoM", route: "/masters/create/bom" },
    { key: "s", label: "Stock Group", route: "/masters/create/stock-group" },
    { key: "t", label: "Stock Category", route: "/masters/create/stock-category" },
    { key: "i", label: "Stock Item", route: "/masters/create/stock-item" },
    { key: "u", label: "Unit of Measure", route: "/masters/create/unit" },
    { key: "d", label: "Godown / Location", route: "/masters/create/godown" },
    { key: "p", label: "Price List", route: "/masters/create/price-list" },
  ],
  "Masters/Alter": [
    { key: "g", label: "Group", route: "/masters/alter/group" },
    { key: "l", label: "Ledger", route: "/masters/alter/ledger" },
    { key: "v", label: "Voucher Type", route: "/masters/alter/voucher-type" },
    { key: "c", label: "Currency", route: "/masters/alter/currency" },
    { key: "k", label: "Cost Category", route: "/masters/alter/cost-category" },
    { key: "n", label: "Cost Centre", route: "/masters/alter/cost-centre" },
    { key: "e", label: "Employee", route: "/masters/alter/employee" },
    { key: "b", label: "BoM", route: "/masters/alter/bom" },
    { key: "s", label: "Stock Group", route: "/masters/alter/stock-group" },
    { key: "t", label: "Stock Category", route: "/masters/alter/stock-category" },
    { key: "i", label: "Stock Item", route: "/masters/alter/stock-item" },
    { key: "u", label: "Unit of Measure", route: "/masters/alter/unit" },
    { key: "d", label: "Godown", route: "/masters/alter/godown" },
    { key: "p", label: "Price List", route: "/masters/alter/price-list" },
  ],
  "Chart of Accounts": [
    { key: "g", label: "Groups", route: "/chart-of-accounts/groups" },
    { key: "l", label: "Ledgers", route: "/chart-of-accounts/ledgers" },
    { key: "s", label: "Stock Groups", route: "/chart-of-accounts/stock-groups" },
    { key: "i", label: "Stock Items", route: "/chart-of-accounts/stock-items" },
  ],
  "Transactions (Vouchers)/Accounting Vouchers": [
    { key: "c", label: "Contra", route: "/transactions/accounting/contra" },
    { key: "m", label: "Payment", route: "/transactions/accounting/payment" },
    { key: "r", label: "Receipt", route: "/transactions/accounting/receipt" },
    { key: "j", label: "Journal", route: "/transactions/accounting/journal" },
    { key: "s", label: "Sales", route: "/transactions/accounting/sales" },
    { key: "o", label: "POS Voucher", route: "/transactions/accounting/pos-voucher" },
    { key: "h", label: "Purchase", route: "/transactions/accounting/purchase" },
    { key: "n", label: "Credit Note", route: "/transactions/accounting/credit-note" },
    { key: "d", label: "Debit Note", route: "/transactions/accounting/debit-note" },
  ],
  "Transactions (Vouchers)/Inventory Vouchers": [
    { key: "r", label: "Receipt Note", route: "/transactions/inventory/receipt-note" },
    { key: "d", label: "Delivery Note", route: "/transactions/inventory/delivery-note" },
    { key: "i", label: "Rejections In", route: "/transactions/inventory/rejections-in" },
    { key: "o", label: "Rejections Out", route: "/transactions/inventory/rejections-out" },
    { key: "j", label: "Stock Journal", route: "/transactions/inventory/stock-journal" },
    { key: "m", label: "Manufacturing", route: "/transactions/inventory/manufacturing" },
    { key: "p", label: "Physical Stock", route: "/transactions/inventory/physical-stock" },
  ],
  "Reports/Financial Statements": [
    { key: "b", label: "Balance Sheet", route: "/reports/financial/balance-sheet" },
    { key: "p", label: "Profit & Loss", route: "/reports/financial/profit-loss" },
    { key: "t", label: "Trial Balance", route: "/reports/financial/trial-balance" },
    { key: "c", label: "Cash Flow", route: "/reports/financial/cash-flow" },
    { key: "f", label: "Fund Flow", route: "/reports/financial/fund-flow" },
  ],
  "Reports/Inventory Books": [
    { key: "i", label: "Stock Item", route: "/reports/inventory-books/stock-item" },
    { key: "g", label: "Stock Group Summary", route: "/reports/inventory-books/stock-group-summary" },
    { key: "o", label: "BoM Register", route: "/reports/inventory-books/bom-register" },
    { key: "p", label: "Production Register", route: "/reports/inventory-books/production-register" },
    { key: "c", label: "Component Consumption", route: "/reports/inventory-books/component-consumption" },
    { key: "m", label: "Stock Group Analysis", route: "/reports/inventory-books/movement-analysis/stock-group" },
    { key: "x", label: "Sales Person Analysis", route: "/reports/inventory-books/movement-analysis/sales-person" },
    { key: "d", label: "Godown Summary", route: "/reports/inventory-books/godown-summary" },
    { key: "b", label: "Batch Summary", route: "/reports/inventory-books/batch-summary" },
  ],
  "Reports/Account Books": [
    { key: "s", label: "Sales Register", route: "/reports/account-books/sales-register" },
    { key: "p", label: "Purchase Register", route: "/reports/account-books/purchase-register" },
    { key: "j", label: "Journal Register", route: "/reports/account-books/journal-register" },
    { key: "d", label: "Debit Note Register", route: "/reports/account-books/debit-note-register" },
    { key: "c", label: "Credit Note Register", route: "/reports/account-books/credit-note-register" },
  ],
  "Reports/Customer Behaviour": [
    { key: "o", label: "Overview", route: "/reports/customer-behaviour/overview" },
    { key: "p", label: "Product-wise", route: "/reports/customer-behaviour/product-wise" },
    { key: "g", label: "Stock Group-wise", route: "/reports/customer-behaviour/stock-group-wise" },
    { key: "c", label: "Category-wise", route: "/reports/customer-behaviour/category-wise" },
  ],
  Utilities: [
    { key: "i", label: "Import Data", route: "/utilities/import-data" },
    { key: "e", label: "Export Data", route: "/utilities/export-data" },
    { key: "b", label: "Banking Utilities", route: "/utilities/banking-utilities" },
    { key: "v", label: "Data Verification", route: "/utilities/data-verification" },
    { key: "r", label: "Rewrite Data", route: "/utilities/rewrite-data" },
    { key: "s", label: "Split Company Data", route: "/utilities/split-company-data" },
  ],
};
